Tokenizing Input
lianasyrkett/CodeU-Summer-2017 pull request #3
Opened 2017-06-01 19:44 UTC by seibelsabrina

Changed the command line input processing to tokenize input before passing it to a command for execution.

2017-06-07 22:12 UTC, efuquen reviewed
I think overall your style is fine, but the code is not working. I get the following error:

http://imgur.com/a/uNUHW

2017-06-12 12:43 UTC, efuquen commented
Looks like none of the commands are recognized: http://i.imgur.com/F7oIEKM.png

Since `exit` isn't working I would take a look at what the `command` variable is being set to, seems like an issue with the `Tokenizer` if that is not getting set to the correct value:

https://github.com/lianasyrkett/CodeU-Summer-2017/pull/3/files#diff-085ee4c5309974341970845d11bcb286L58

2017-06-12 15:12 UTC, seibelsabrina commented
Did some small changes and the commands look like they are being recognized now. PTAL

2017-06-12 19:18 UTC, seibelsabrina commented
Fixed Tokenizer.java as discussed in our meeting. Also resolved merge conflict. PTAL

2017-06-19 16:55 UTC, efuquen requested changes
When I removed the extra `info` command the code works like before but the quoting is not working properly. With single quotes it saves the whole user name with the quotes in it and double quotes cause the program to exit. output i get below:

```
>>> u-add efuquen
>>> u-list
USER efuquen (UUID:1.3793251597)
>>> u-add 'foobar'
>>> u-list
USER 'foobar' (UUID:1.2791704588)
USER efuquen (UUID:1.3793251597)
>>> u-add "blah"
Run PASSED
efuquen-macbookpro:CodeU-Summer-2017 efuquen$
```

2017-06-19 16:55 UTC, efuquen commented on src/codeu/chat/util/Tokenizer.java
> +		} if (remaining() <= 0) {
Don't put the if statement right after the curly bracket of the `while` loop like this, it makes it confusing to read. The `if` statement should start on it's own line.

2017-06-19 16:55 UTC, efuquen commented on src/codeu/chat/util/Tokenizer.java
> +			readWithNoQuotes();
You should be returning on each one of the branches of the `if` statement.

2017-06-19 16:55 UTC, efuquen commented on src/codeu/chat/util/Tokenizer.java
> +		return "";
If you return on each branch you shouldn't need this last return.

2017-06-19 16:55 UTC, efuquen commented on src/codeu/chat/util/Tokenizer.java
> +		} else if (peek() == '"') {
You should accept single quotes too, so add it to the conditional. Should be something like:

`} else if (peek() == '"' || peek() == '\'') {`

2017-06-19 16:55 UTC, efuquen commented on src/codeu/chat/util/Tokenizer.java
> +		if (read() != '"') {
To accept single quotes do:
```
char openingQuote = read();
if (openingQuote != '"' && openingQuote != '\'') {
```

2017-06-19 16:55 UTC, efuquen commented on src/codeu/chat/util/Tokenizer.java
> +		while (peek() != '"') {
Similar to above, to accept single quotes do:
`while(peek() != '"' && peek() != '\'') {`

2017-06-19 16:55 UTC, efuquen commented on src/codeu/chat/client/commandline/Chat.java
> +      public void invoke(List<String> args) {
This is not compiling for me. Line 128 has an extra `panel.register("info", new Panel.Command() {` that is using the Scanner. This most likely came in when you merged in master to resolve the conflicts. I'm pasting the error below (:

```
src/codeu/chat/client/commandline/Chat.java:128: error: <anonymous codeu.chat.client.commandline.Chat$2> is not abstract and does not override abstract method invoke(List<String>) in Command
    panel.register("info", new Panel.Command() {
                                               ^
src/codeu/chat/client/commandline/Chat.java:129: error: method does not override or implement a method from a supertype
      @Override
      ^
```

2017-06-26 17:53 UTC, merged